utils: utils.h utils.cpp
	c++ -std=c++11 -stdlib=libc++ -o utils.o -c utils.cpp
	c++ -std=c++11 -stdlib=libc++ -o run_utils run_utils.cpp utils.o
	
athlete: athlete.h athlete.cpp 
	c++ -std=c++11 -stdlib=libc++ -o utils.o -c utils.cpp
	c++ -std=c++11 -stdlib=libc++ -o athlete.o -c athlete.cpp
	c++ -std=c++11 -stdlib=libc++ -o run_athlete run_athlete.cpp utils.o athlete.o 
